apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.pg_bouncer.app_name }}-pgb-config
  namespace: {{ .Values.common.cluster_namespace }}
data:
  pgbouncer.ini: |
    [databases]
    {{ .Values.pg_bouncer.env.db_name }} = host={{ .Values.pg_bouncer.env.db_host }} port=5432 dbname={{ .Values.pg_bouncer.env.db_name }}

    [pgbouncer]
    listen_addr = 0.0.0.0
    listen_port = {{ .Values.pg_bouncer.service.pgb_port }}
    auth_type = md5
    auth_file = /bitnami/pgbouncer/conf/userlist.txt
    pool_mode = transaction
    max_client_conn = 2000
    autodb_idle_timeout = 3600
    default_pool_size = 20
    max_db_connections = 200
    max_user_connections = 200
