[tox]
envlist = py3
skipsdist=True

[coverage:html]
directory=coverage

[coverage:report]
show_missing=True

[coverage:run]
omit = apps/**/migrations/*, apps/**/factories/*, assets/*, config/*, docs/*, scripts/*
plugins =
    django_coverage_plugin

[pytest]
DJANGO_SETTINGS_MODULE=config.settings.test
norecursedirs= node_modules venv build env bin .cache .tox
addopts = --ds=config.settings.test --cov=apps --cov-fail-under=50 --cov-report=html --cov-report=term-missing -n auto --junitxml='junitxml_report/report.xml' -v  --durations=10 --cache-clear --create-db -p no:sugar
minversion = 3.10.0
log_cli = 1
log_cli_date_format=%Y-%m-%d %H:%M:%S
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_cli_level = ERROR

[flake8]
exclude = .tox,.git,*/migrations/*,*/static/CACHE/*,docs,node_modules,venv
max_line_length = 79
max_complexity = 7

[isort]
extend_skip = docs
extend_skip_glob = */migrations/*,*/static/CACHE/*
profile = black

[testenv]
basepython = python3
passenv =
    DJANGO_ADMIN_URL
    DJANGO_ALLOWED_HOSTS
    DJANGO_DEBUG
    DJANGO_SECRET_KEY
    DJANGO_SETTINGS_MODULE
    POSTGRES_DB
    POSTGRES_HOST
    POSTGRES_PASSWORD
    POSTGRES_PORT
    POSTGRES_USER
    TEST_POSTGRES_DB
    TEST_POSTGRES_HOST
    TEST_POSTGRES_PASSWORD
    TEST_POSTGRES_PORT
    TEST_POSTGRES_USER
    SENTRY_DSN

deps =
    -rrequirements.txt

commands =
    python manage.py collectstatic --no-input
    flake8 apps/
    coverage erase
    pytest --cov=apps -n auto --durations=100 {posargs}
    coverage html
    coverage report
