# Generated by Django 4.0.4 on 2022-05-30 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_initial'),
        ('sql_sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceversion',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.genericsource'),
        ),
        migrations.AddField(
            model_name='sourceversion',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simplesqlmetadata',
            name='applicable_versions',
            field=models.ManyToManyField(to='sql_sources.sourceversion'),
        ),
        migrations.AddField(
            model_name='simplesqlmetadata',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simplesqlmetadata',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.genericsource'),
        ),
        migrations.AddField(
            model_name='simplesqlmetadata',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
