apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ .Chart.Name }}-ingress
    namespace: {{ .Values.namespace }}
    annotations:
        cert-manager.io/cluster-issuer: {{ .Values.networking.issuer.name }}
        konghq.com/protocols: "http,https"
        konghq.com/https-redirect-status-code: "308"
spec:
    ingressClassName: kong
    tls:
        - secretName: {{ .Chart.Name }}-tls
          hosts:
              - {{ .Values.networking.ingress.domain }}
    rules:
        - host: {{ .Values.networking.ingress.domain }}
          http:
              paths:
                  - path: /
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: {{ .Chart.Name }}-service
                            port:
                                number: {{ .Values.image.containerPort }}