apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}

  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.image.containerPort }}
      targetPort: {{ .Values.image.containerPort }}
      nodePort: {{ .Values.service.node_port }}

