# Generated by Django 4.0.4 on 2022-06-09 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlextractmetadata',
            name='applicable_source_versions',
            field=models.ManyToManyField(related_name='available_versions', to='sql_data.datasourceversion', verbose_name='Applicable data source versions'),
        ),
        migrations.AlterField(
            model_name='sqlextractmetadata',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='available_extracts', to='sql_data.sqldatabasesource'),
        ),
        migrations.AlterField(
            model_name='sqluploadchunk',
            name='upload_metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_chunks', to='sql_data.sqluploadmetadata'),
        ),
        migrations.AlterField(
            model_name='sqluploadmetadata',
            name='extract_metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='sql_data.sqlextractmetadata'),
        ),
    ]
