common:
  project_id: "project-id"
  cluster_name: "cluster-name"
  compute_zone: "compute-zone"
  cluster_namespace: "work-namespace"
  service_account_key: "base64_encoded_sa_key"
  service_account_name: "iam-service-account-key"

cloud_sdk:
  ttl_after_success: 600
  image:
    repository: gcr.io/google.com/cloudsdktool/cloud-sdk
    tag: "459.0.0"
    pull_policy: IfNotPresent

django:
  app_name: django
  replica_count: 2
  image:
    repository: repo
    tag: commit_sha
    pull_policy: Always
    container_port: 8080
  service:
    port: 80
    type: NodePort
  configmap:
    config_name: "config_name"
  secrets:
    secrets_name: "secrets_name"
  env:
    django_settings_module: django_settings_module
    postgres_host: postgres_host
    postgres_port: postgres_port

cloud_sql:
  app_name: cloudsql-proxy
  image:
    repository: gcr.io/cloud-sql-connectors/cloud-sql-proxy
    tag: "2.6.0"
  env:
    cloudsql_connection_instance: "cloudsql_connection_instance"

pg_bouncer:
  app_name: pgbouncer
  replica_count: 2
  image:
    repository: bitnami/pgbouncer
    tag: "1.19.1"
  service:
    type: LoadBalancer
    pgb_port: 6432
    pgb_target_port: 6432
  env:
    db_host: "127.0.0.1"
    db_port: 5432
    db_name: "database_name"
    db_user: "database_user"
    db_password: "database_password"

secret_manager:
  file_name: secret_manager_file_name

ingress:
  app_name: ingress
  networking:
    domain: ""
    issuer:
      name: "letsencrypt-staging"
      acme:
        server: "https://acme-v02.api.letsencrypt.org/directory"
        email: "support@mail.fahariyajamii.org"
