# Generated by Django 4.1 on 2022-08-17 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "sql_data",
            "0002_alter_sqlextractmetadata_applicable_source_versions_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sqluploadchunk",
            name="finish_time",
        ),
        migrations.RemoveField(
            model_name="sqluploadchunk",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="sqluploadmetadata",
            name="chunks",
        ),
        migrations.RemoveField(
            model_name="sqluploadmetadata",
            name="made_on",
        ),
        migrations.AddField(
            model_name="sqluploadmetadata",
            name="finish_time",
            field=models.DateTimeField(
                blank=True,
                help_text="The completion time of this upload this. An upload will only be considered complete once this value is non-null.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sqluploadmetadata",
            name="start_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="The time that this upload commenced.",
            ),
            preserve_default=False,
        ),
    ]
