apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.common.service_account_name }}
  namespace: {{ .Values.common.cluster_namespace }}
type: Opaque
data:
  # base64 -w 0 /path/to/sa_key.json
  service_account.json: {{ .Values.common.service_account_key }}
