apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.pg_bouncer.app_name }}-db-config
data:
  POSTGRESQL_DB: {{ .Values.pg_bouncer.env.db_name }}
  POSTGRESQL_USERNAME: {{ .Values.pg_bouncer.env.db_user }}
  POSTGRESQL_PASSWORD: {{ .Values.pg_bouncer.env.db_password }}
  POSTGRESQL_HOST: {{ .Values.pg_bouncer.env.db_host }}
  POSTGRESQL_PORT: {{ .Values.pg_bouncer.env.db_port | toString | quote }}
